import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useRef, useState } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { useTimeline } from "./hooks/useTimeline";
import { useCssSeek } from "./hooks/useCssSeek";
import { useBgm } from "./hooks/useBgm";
import { CHAPTERS } from "./registry/chapters";

function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

/** Read `?t=<seconds>` from the URL. Returns null if not in seek mode. */
function readSeekTime(): number | null {
  if (typeof window === "undefined") return null;
  const v = new URLSearchParams(window.location.search).get("t");
  if (v === null) return null;
  const n = parseFloat(v);
  return Number.isFinite(n) ? n : null;
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const { seekToTime, boundaries, totalDuration } = useTimeline(CHAPTERS);

  const [seekTime] = useState<number | null>(() => readSeekTime());
  const isSeekMode = seekTime !== null;
  const seekResult = isSeekMode ? seekToTime(seekTime!) : null;

  const activeChapterIdx = isSeekMode && seekResult ? seekResult.chapter : stepper.cursor.chapter;
  const activeStep = isSeekMode && seekResult ? seekResult.step : stepper.cursor.step;
  const stepTime = seekResult?.stepTime;

  const ch = CHAPTERS[activeChapterIdx]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[activeStep] ?? "";

  const { mode, setMode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();
  const isLastStep = stepper.globalIndex === stepper.totalGlobal - 1;
  const [isStandalone, setIsStandalone] = useState(false);
  useEffect(() => { setIsStandalone(window.self === window.top); }, []);

  // Playback controls driven by parent Studio via postMessage.
  const [playbackPaused, setPlaybackPaused] = useState(false);
  const [playbackSpeed, setPlaybackSpeed] = useState(1);
  const [editMode, setEditMode] = useState(false);
  const stepperRef = useRef(stepper);
  stepperRef.current = stepper;

  // ── Edit mode overlay ──────────────────────────────────────────────────────
  useEffect(() => {
    if (!editMode) return;

    let hovered: HTMLElement | null = null;
    let selected: HTMLElement | null = null;

    const IGNORE_TAGS = new Set(["HTML", "BODY", "SCRIPT", "STYLE", "HEAD"]);
    const NO_ADVANCE = "[data-no-advance]";

    function getChapterAndStep(): { chapterId: string; stepIndex: number } {
      const w = window as unknown as Record<string, unknown>;
      const boundaries = (w.__hfStepBoundaries as Array<{ chapter: number; step: number }>) ?? [];
      const globalIdx = (w.__currentGlobalIndex as number) ?? 0;
      const b = boundaries[globalIdx];
      const chapters = (w.__chapters as Array<{ id: string }>) ?? [];
      return {
        chapterId: chapters[b?.chapter ?? 0]?.id ?? String(b?.chapter ?? 0),
        stepIndex: b?.step ?? 0,
      };
    }

    function getXPath(el: HTMLElement): string {
      if (!el.parentElement) return el.tagName.toLowerCase();
      const siblings = Array.from(el.parentElement.children).filter(
        (c) => c.tagName === el.tagName
      );
      const idx = siblings.indexOf(el) + 1;
      return `${getXPath(el.parentElement as HTMLElement)}/${el.tagName.toLowerCase()}[${idx}]`;
    }

    function sendSelected(el: HTMLElement) {
      const rect = el.getBoundingClientRect();
      const { chapterId, stepIndex } = getChapterAndStep();
      window.parent.postMessage({
        type: "element-selected",
        data: {
          tagName: el.tagName.toLowerCase(),
          className: el.className,
          textContent: el.textContent?.trim().slice(0, 100) ?? "",
          rect: { x: rect.left, y: rect.top, width: rect.width, height: rect.height },
          xpath: getXPath(el),
          chapterId,
          stepIndex,
          isConditionalStep: el.closest("[data-step]") !== null,
        },
      }, "*");
    }

    function onMouseOver(e: MouseEvent) {
      const el = e.target as HTMLElement;
      if (IGNORE_TAGS.has(el.tagName) || el.closest(NO_ADVANCE)) return;
      if (el === hovered) return;
      if (hovered) hovered.style.outline = "";
      hovered = el;
      el.style.outline = "2px dashed rgba(99,102,241,0.6)";
      el.style.cursor = "pointer";
    }

    function onMouseOut(e: MouseEvent) {
      const el = e.target as HTMLElement;
      if (el === hovered && el !== selected) {
        el.style.outline = "";
        el.style.cursor = "";
      }
    }

    function onClick(e: MouseEvent) {
      const el = e.target as HTMLElement;
      if (el.closest(NO_ADVANCE)) return;
      e.stopPropagation();
      e.preventDefault();
      if (IGNORE_TAGS.has(el.tagName)) return;
      if (selected && selected !== el) {
        selected.style.outline = hovered === selected ? "2px dashed rgba(99,102,241,0.6)" : "";
      }
      selected = el;
      el.style.outline = "2px solid rgba(99,102,241,1)";
      sendSelected(el);
    }

    function onDblClick(e: MouseEvent) {
      const el = e.target as HTMLElement;
      if (IGNORE_TAGS.has(el.tagName) || el.closest(NO_ADVANCE)) return;

      // Find the nearest editable leaf: element that has visible text
      // and no significant element children (only text/inline nodes)
      function findEditableLeaf(node: HTMLElement): HTMLElement | null {
        if (!node.textContent?.trim()) return null;
        const children = Array.from(node.childNodes);
        const hasBlockChild = children.some(
          (c) => c.nodeType === Node.ELEMENT_NODE &&
            !["SPAN","EM","STRONG","B","I","BR","CODE","MARK"].includes((c as HTMLElement).tagName)
        );
        if (hasBlockChild) return null;
        if (children.some((c) => c.nodeType === Node.TEXT_NODE && c.textContent?.trim())) {
          return node;
        }
        // Try immediate inline children
        for (const c of children) {
          if (c.nodeType === Node.ELEMENT_NODE) {
            const found = findEditableLeaf(c as HTMLElement);
            if (found) return found;
          }
        }
        return null;
      }

      const target = findEditableLeaf(el) ?? (
        el.childNodes.length === 1 && el.firstChild?.nodeType === Node.TEXT_NODE ? el : null
      );
      if (!target) return;

      e.stopPropagation();
      e.preventDefault();

      target.contentEditable = "true";
      target.focus();
      // Select all text
      const range = document.createRange();
      range.selectNodeContents(target);
      const sel = window.getSelection();
      sel?.removeAllRanges();
      sel?.addRange(range);
      target.style.outline = "2px solid rgba(99,102,241,1)";
      target.style.borderRadius = "3px";
      const oldText = target.textContent ?? "";

      function onBlur() {
        target.contentEditable = "inherit";
        target.style.borderRadius = "";
        const newText = target.textContent ?? "";
        if (newText !== oldText) {
          window.parent.postMessage({
            type: "text-changed",
            data: {
              xpath: getXPath(target),
              oldText,
              newText,
              className: target.className,
              tagName: target.tagName.toLowerCase(),
            },
          }, "*");
        }
        target.removeEventListener("blur", onBlur);
        target.removeEventListener("keydown", onKey);
      }
      function onKey(ev: KeyboardEvent) {
        if (ev.key === "Enter") { ev.preventDefault(); target.blur(); }
        if (ev.key === "Escape") { target.textContent = oldText; target.blur(); }
      }
      target.addEventListener("blur", onBlur);
      target.addEventListener("keydown", onKey);
    }

    document.addEventListener("mouseover", onMouseOver);
    document.addEventListener("mouseout", onMouseOut);
    document.addEventListener("click", onClick, true);
    document.addEventListener("dblclick", onDblClick, true);
    window.parent.postMessage({ type: "edit-mode-ready" }, "*");
    window.parent.postMessage({
      type: "chapters-info",
      data: CHAPTERS.map((ch) => ({ id: ch.id, title: ch.title, stepCount: ch.narrations.length })),
    }, "*");

    return () => {
      document.removeEventListener("mouseover", onMouseOver);
      document.removeEventListener("mouseout", onMouseOut);
      document.removeEventListener("click", onClick, true);
      document.removeEventListener("dblclick", onDblClick, true);
      if (hovered) hovered.style.outline = "";
      if (selected && selected !== hovered) selected.style.outline = "";
    };
  }, [editMode]);

  // Receive commands from Studio.
  useEffect(() => {
    if (window.self === window.top) return;
    function onMsg(e: MessageEvent) {
      const msg = e.data as { type?: string; chapter?: number; rate?: number; step?: number };
      if (msg.type === "start-auto") {
        setMode("auto");
        setAutoStarted(true);
        setPlaybackPaused(false);
      } else if (msg.type === "pause") {
        setPlaybackPaused(true);
      } else if (msg.type === "resume") {
        setPlaybackPaused(false);
      } else if (msg.type === "seek-chapter" && typeof msg.chapter === "number") {
        stepperRef.current.jumpToChapter(msg.chapter, 0);
      } else if (msg.type === "set-speed" && typeof msg.rate === "number") {
        setPlaybackSpeed(msg.rate);
      } else if (msg.type === "edit-mode") {
        setEditMode(true);
      } else if (msg.type === "exit-edit-mode") {
        setEditMode(false);
      } else if (msg.type === "seek-to-step" && typeof msg.chapter === "number" && typeof msg.step === "number") {
        stepperRef.current.jumpToChapter(msg.chapter, msg.step);
      }
    }
    window.addEventListener("message", onMsg);
    return () => window.removeEventListener("message", onMsg);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Emit step-changed to Studio whenever the active step changes.
  useEffect(() => {
    if (window.self === window.top) return;
    // Expose for edit-mode overlay
    const w = window as unknown as Record<string, unknown>;
    w.__currentGlobalIndex = stepper.globalIndex;
    w.__chapters = CHAPTERS;
    w.__hfStepBoundaries = boundaries;
    window.parent.postMessage(
      {
        type: "step-changed",
        data: {
          globalIndex: stepper.globalIndex,
          totalGlobal: stepper.totalGlobal,
          chapter: stepper.cursor.chapter,
          chapterTitle: CHAPTERS[stepper.cursor.chapter]?.title ?? "",
          step: stepper.cursor.step,
          startSec: boundaries[stepper.globalIndex]?.startSec ?? 0,
          stepDuration: boundaries[stepper.globalIndex]?.duration ?? 3,
          totalDuration,
        },
      },
      "*"
    );
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stepper.globalIndex]);

  // CSS seek: freeze all @keyframe animations at stepTime within the stage
  const stageRef = useRef<HTMLDivElement>(null);
  useCssSeek(stageRef, isSeekMode ? (stepTime ?? 0) : null);

  // Signal seek-readiness after one rAF (DOM rendered + seek applied)
  useEffect(() => {
    if (!isSeekMode) return;
    const id = requestAnimationFrame(() => {
      (window as unknown as Record<string, unknown>).__hfSeekReady = true;
    });
    return () => cancelAnimationFrame(id);
  }, [isSeekMode, seekTime]);

  const audioSrc =
    mode === "manual" || stepText === "" || isSeekMode
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${activeStep + 1}.mp3`;

  const onAutoAdvance = useCallback(() => {
    if (isLastStep) {
      (window as unknown as Record<string, unknown>).__presentationDone = true;
      if (window.self !== window.top) {
        window.parent.postMessage({ type: "presentation-end" }, "*");
      }
    }
    stepper.next();
  }, [stepper, isLastStep]);

  useAudioPlayer({
    src: audioSrc,
    mode: isSeekMode ? "manual" : mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
    paused: playbackPaused,
    playbackRate: playbackSpeed,
  });

  useBgm({ autoStarted, paused: playbackPaused, playbackRate: playbackSpeed, isSeekMode });

  // Minimal shell for headless seek-mode rendering — no interactive chrome
  if (isSeekMode) {
    return (
      <div ref={stageRef}>
        <Stage onAdvance={() => {}}>
          <div key={`${ch.id}-${activeStep}`} className="scene">
            <Cmp step={activeStep} stepTime={stepTime} />
          </div>
        </Stage>
      </div>
    );
  }

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} stepTime={stepTime} />
        </div>
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted && !playbackPaused}
        onStart={() => setAutoStarted(true)}
      />
      {isLastStep && isStandalone && (
        <div
          style={{
            position: "fixed",
            bottom: "2rem",
            right: "2rem",
            zIndex: 200,
            opacity: 0,
            animation: "fadeIn 0.6s 0.8s forwards",
          }}
        >
          <style>{`@keyframes fadeIn { to { opacity: 1; } }`}</style>
          <button
            data-no-advance
            onClick={() => {
              if (window.opener && !window.opener.closed) {
                window.close();
                return;
              }
              window.location.href = "http://localhost:3100";
            }}
            style={{
              background: "var(--surface-2, rgba(255,255,255,0.1))",
              color: "var(--text-2, rgba(255,255,255,0.6))",
              border: "1px solid var(--rule, rgba(255,255,255,0.15))",
              borderRadius: "0.75rem",
              padding: "0.5rem 1.25rem",
              fontSize: "0.85rem",
              cursor: "pointer",
              backdropFilter: "blur(8px)",
              letterSpacing: "0.02em",
              transition: "color 0.2s",
            }}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLButtonElement).style.color = "var(--text, #fff)";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.color = "var(--text-2, rgba(255,255,255,0.6))";
            }}
          >
            ← 返回
          </button>
        </div>
      )}
    </>
  );
}
